# Generated by Django 3.2.13 on 2022-05-19 15:48

from django.db import migrations, models
import django.db.models.deletion
import utils.FileFieldValidators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(verbose_name='video created')),
                ('url', models.FileField(upload_to='djserver/upload/video', validators=[utils.FileFieldValidators.validate_file_extension, utils.FileFieldValidators.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.ImageField(upload_to='djserver/upload/gif')),
                ('create_time', models.DateTimeField(verbose_name='gif created')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='video2gif.video')),
            ],
        ),
    ]
