# Generated by Django 4.0.4 on 2022-04-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video2gif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('url', models.FileField(upload_to='djserver/upload/video')),
                ('create_time', models.DateTimeField(verbose_name='video created')),
            ],
        ),
        migrations.AlterField(
            model_name='gif',
            name='create_time',
            field=models.DateTimeField(verbose_name='gif created'),
        ),
        migrations.AlterField(
            model_name='gif',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='gif',
            name='Gif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='video2gif.video'),
        ),
    ]
