# Generated by Django 3.2.13 on 2022-05-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video2gif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='video',
        ),
    ]
