# Generated by Django 4.0.4 on 2022-05-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video2gif', '0002_video_alter_gif_create_time_alter_gif_name_gif_gif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gif',
            old_name='Gif',
            new_name='video',
        ),
    ]
